# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: JesseTG/rm@v1.0.0
        with:
          # The file path to remove
          path: .git
          
      - uses: JesseTG/rm@v1.0.0
        with:
          # The file path to remove
          path: .github

      - uses: actions/upload-artifact@v1
        with:
          name: latest
          path: ${{ github.workspace }}

      - uses: nickatnight/releases-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          # Name of branch to release from
          branch: main
          # Name of the release
          name: Release name
          # Message for the release
          message: Release message
          # Draft or naw?
          #draft: # optional, default is false
          # Pre-release or naw
          #prerelease: # optional, default is false
          # Name of tag
          tag: v1.1
